# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: mvn compile
  displayName: 'compile'

- script: mvn test
  displayName: 'test'
- script: mvn package
  displayName: 'package'
